env: dev
server:
  port: 8080
  timezoneLoc: Asia/Shanghai
  # gin mode: debug, release, test
  ginMode: debug
db:
  user: root
  pass: root
  host: 127.0.0.1
  port: 3306
  name: test
  maxConnect: 10
  maxIdle: 10
  showSql: true
redis:
  host: 127.0.0.1:6379
  pass: pass
  db: 0
log:
  path: /tmp/log
  # 0-PanicLevel 1-FatalLevel 2-ErrorLevel 3-WarnLevel 4-InfoLevel 5-DebugLevel 6-TraceLevel
  level: 5